xflags::xflags! {
    src "src/flags.rs"

    cmd pinka {
        /// Launch the nth server from the config file
        optional -s, --server N: usize

        cmd serve {
            /// Launch server in bootstrap mode
            optional --bootstrap
        }
        cmd raft {
            cmd dump {
                /// Start from index
                optional --from index: usize
            }
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Pinka {
    pub server: Option<usize>,
    pub subcommand: PinkaCmd,
}

#[derive(Debug)]
pub enum PinkaCmd {
    Serve(Serve),
    Raft(Raft),
}

#[derive(Debug)]
pub struct Serve {
    pub bootstrap: bool,
}

#[derive(Debug)]
pub struct Raft {
    pub subcommand: RaftCmd,
}

#[derive(Debug)]
pub enum RaftCmd {
    Dump(Dump),
}

#[derive(Debug)]
pub struct Dump {
    pub from: Option<usize>,
}

impl Pinka {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
