name: Build and Push Container

on:
  push:
    branches:
      - main
      - staging
      - v*
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

jobs:
  build_container:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Buildah
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y buildah
      - name: Buildah Action
        run: |
          buildah build --tag oci-archive:pinka-${{ matrix.arch }}.ociarchive .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinka-${{ matrix.arch }}
          path: pinka-${{ matrix.arch }}.ociarchive
          retention-days: 1
  build_manifest:
    runs-on: ubuntu-latest
    needs: build_container
    steps:
      - name: Install Podman
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y podman
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: artifact
          merge-multiple: true
      - name: Create Manifest
        env:
          TAG: ${{ github.ref_name }}
        run: |
          podman manifest create quay.io/pinka/pinka:$TAG oci-archive:artifact/pinka-amd64.ociarchive oci-archive:artifact/pinka-arm64.ociarchive
      - name: Push Manifest to Quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: pinka
          tags: ${{ github.ref_name }}
          registry: quay.io/pinka
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
